/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedIncomingIndexRouteImport } from './routes/_authenticated/incoming.index'
import { Route as AuthenticatedGradingIndexRouteImport } from './routes/_authenticated/grading.index'
import { Route as AuthenticatedIncomingIdRouteImport } from './routes/_authenticated/incoming.$id'
import { Route as AuthenticatedGradingIdRouteImport } from './routes/_authenticated/grading.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomingIndexRoute =
  AuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGradingIndexRoute =
  AuthenticatedGradingIndexRouteImport.update({
    id: '/grading/',
    path: '/grading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIdRoute = AuthenticatedIncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGradingIdRoute = AuthenticatedGradingIdRouteImport.update({
  id: '/grading/$id',
  path: '/grading/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/grading/': typeof AuthenticatedGradingIndexRoute
  '/incoming/': typeof AuthenticatedIncomingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/grading': typeof AuthenticatedGradingIndexRoute
  '/incoming': typeof AuthenticatedIncomingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/grading/$id': typeof AuthenticatedGradingIdRoute
  '/_authenticated/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/_authenticated/grading/': typeof AuthenticatedGradingIndexRoute
  '/_authenticated/incoming/': typeof AuthenticatedIncomingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/people'
    | '/grading/$id'
    | '/incoming/$id'
    | '/grading/'
    | '/incoming/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/people'
    | '/grading/$id'
    | '/incoming/$id'
    | '/grading'
    | '/incoming'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/daybook'
    | '/_authenticated/people'
    | '/_authenticated/grading/$id'
    | '/_authenticated/incoming/$id'
    | '/_authenticated/grading/'
    | '/_authenticated/incoming/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/': {
      id: '/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/incoming/'
      preLoaderRoute: typeof AuthenticatedIncomingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/': {
      id: '/_authenticated/grading/'
      path: '/grading'
      fullPath: '/grading/'
      preLoaderRoute: typeof AuthenticatedGradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/$id': {
      id: '/_authenticated/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof AuthenticatedIncomingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/$id': {
      id: '/_authenticated/grading/$id'
      path: '/grading/$id'
      fullPath: '/grading/$id'
      preLoaderRoute: typeof AuthenticatedGradingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedGradingIdRoute: typeof AuthenticatedGradingIdRoute
  AuthenticatedIncomingIdRoute: typeof AuthenticatedIncomingIdRoute
  AuthenticatedGradingIndexRoute: typeof AuthenticatedGradingIndexRoute
  AuthenticatedIncomingIndexRoute: typeof AuthenticatedIncomingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedGradingIdRoute: AuthenticatedGradingIdRoute,
  AuthenticatedIncomingIdRoute: AuthenticatedIncomingIdRoute,
  AuthenticatedGradingIndexRoute: AuthenticatedGradingIndexRoute,
  AuthenticatedIncomingIndexRoute: AuthenticatedIncomingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
